<?php
/**
 * TreeIR -> Diagnostics.
 *
 * Pure by design: validate() is a function of (decoded body, blocks map,
 * server fingerprint) and touches no globals, so tests/bootstrap-lite.php can
 * drive it offline against fixtures/registry-snapshot.json. Only
 * validate_request() reaches into WordPress.
 *
 * Semantics are pinned by CONTRACT.md section 5. In particular:
 *  - E_TREE_SCHEMA stops all further checks.
 *  - E_EPOCH_MISMATCH does not; every other check still runs.
 *  - the children of an E_UNKNOWN_BLOCK node are not further checked.
 *  - W_STATIC_NEEDS_HARNESS is emitted once per distinct static block name.
 *  - attribute checking is registry-shape only. No source-based HTML semantics.
 *
 * @package x-companion
 */

defined( 'ABSPATH' ) || exit;

/**
 * Tree IR validator.
 */
final class X_Companion_Validator {

	/**
	 * The exact fix_hint string pinned by the contract for W_STATIC_NEEDS_HARNESS.
	 */
	const FIX_HINT_STATIC = 'canonical markup must come from harness compile, do not hand-serialize';

	/**
	 * Attribute keys generated by block supports. Never W_ATTR_UNKNOWN.
	 *
	 * Pinned by CONTRACT.md section 5.
	 *
	 * @var string[]
	 */
	const GLOBAL_ATTRIBUTES = array(
		'className',
		'style',
		'lock',
		'metadata',
		'align',
		'anchor',
		'backgroundColor',
		'textColor',
		'gradient',
		'fontSize',
		'fontFamily',
		'borderColor',
		'layout',
		'templateLock',
	);

	/**
	 * BlockNode keys allowed by the TreeIR schema. additionalProperties: false.
	 *
	 * @var string[]
	 */
	const BLOCK_NODE_KEYS = array( 'name', 'attributes', 'innerBlocks' );

	/**
	 * Block name pattern from the TreeIR schema.
	 */
	const BLOCK_NAME_PATTERN = '#^[a-z0-9-]+/[a-z0-9-]+$#';

	/**
	 * Distinct static block names already reported this run.
	 *
	 * @var array<string,bool>
	 */
	private static $static_seen = array();

	/**
	 * Accumulated diagnostics for the current run.
	 *
	 * @var array
	 */
	private static $diagnostics = array();

	/**
	 * Platform context for binding checks: binding_sources (string[] | null
	 * when unknown) and bindable (block name => attribute list).
	 *
	 * @var array
	 */
	private static $platform = array(
		'binding_sources' => null,
		'bindable'        => array(),
	);

	/**
	 * No hooks. Present so the bootstrap loader can call ::init() uniformly.
	 *
	 * @return void
	 */
	public static function init(): void {}

	/**
	 * Validate a decoded TreeIR body against a blocks map.
	 *
	 * @param mixed  $tree               Decoded request body (associative).
	 * @param array  $blocks             Manifest-shaped blocks map, name => entry.
	 * @param string $server_fingerprint The current epoch.
	 * @return array Diagnostics document.
	 */
	public static function validate( $tree, array $blocks, string $server_fingerprint, array $platform = array() ): array {
		self::$static_seen = array();
		self::$diagnostics = array();
		self::$platform    = array(
			// null = unknown (offline / v1 context): binding-source existence
			// is then not checkable and E_BINDING_UNKNOWN is skipped.
			'binding_sources' => array_key_exists( 'binding_sources', $platform ) ? $platform['binding_sources'] : null,
			'bindable'        => is_array( $platform['bindable'] ?? null ) ? $platform['bindable'] : array(),
		);

		$as_map   = self::to_map( $tree );
		$epoch    = ( isset( $as_map['epoch'] ) && is_string( $as_map['epoch'] ) ) ? $as_map['epoch'] : null;
		$epoch_ok = ( null !== $epoch && $epoch === $server_fingerprint );

		$schema_errors = self::check_schema( $tree );

		if ( ! empty( $schema_errors ) ) {
			// E_TREE_SCHEMA stops all further checks.
			return self::document( $schema_errors, $epoch_ok, $server_fingerprint );
		}

		if ( ! $epoch_ok ) {
			self::add(
				'E_EPOCH_MISMATCH',
				'error',
				'/epoch',
				sprintf(
					'Tree was generated against epoch "%s" but this instance is at "%s".',
					(string) $epoch,
					$server_fingerprint
				),
				'refetch GET /manifest, regenerate against the new epoch, then revalidate'
			);
		}

		self::walk( $as_map['blocks'], '/blocks', $blocks, null, array() );

		return self::document( self::$diagnostics, $epoch_ok, $server_fingerprint );
	}

	/**
	 * Validate against the live registry.
	 *
	 * @param mixed $tree Decoded request body.
	 * @return array Diagnostics document.
	 */
	public static function validate_request( $tree ): array {
		$manifest = X_Companion_Manifest::get_manifest();
		$blocks   = is_array( $manifest['blocks'] ?? null ) ? $manifest['blocks'] : array();

		$platform = array();
		$bindings = $manifest['bindings'] ?? null;
		if ( $bindings instanceof stdClass ) {
			$bindings = (array) $bindings;
		}
		if ( is_array( $bindings ) ) {
			$sources = array();
			foreach ( (array) ( $bindings['sources'] ?? array() ) as $source ) {
				$source = is_array( $source ) ? $source : (array) $source;
				if ( '' !== (string) ( $source['name'] ?? '' ) ) {
					$sources[] = (string) $source['name'];
				}
			}
			$platform['binding_sources'] = $sources;

			$bindable = $bindings['bindable_attributes'] ?? array();
			if ( $bindable instanceof stdClass ) {
				$bindable = (array) $bindable;
			}
			$platform['bindable'] = is_array( $bindable ) ? $bindable : array();
		}

		return self::validate( $tree, $blocks, (string) ( $manifest['fingerprint'] ?? '' ), $platform );
	}

	/*
	 * -------------------------------------------------------------------
	 * Schema
	 * -------------------------------------------------------------------
	 */

	/**
	 * Hand-written TreeIR schema walk.
	 *
	 * The shape is small and closed, and the pointer for every failure has to
	 * be exact, so this is written out rather than delegated. Every failure is
	 * E_TREE_SCHEMA.
	 *
	 * @param mixed $tree Decoded body.
	 * @return array Diagnostics (possibly empty).
	 */
	public static function check_schema( $tree ): array {
		$errors = array();

		if ( ! self::is_json_object( $tree ) ) {
			return array( self::make( 'E_TREE_SCHEMA', 'error', '/', 'Body must be a TreeIR object.' ) );
		}

		$tree = self::to_map( $tree );

		foreach ( array( 'version', 'epoch', 'blocks' ) as $required ) {
			if ( ! array_key_exists( $required, $tree ) ) {
				$errors[] = self::make( 'E_TREE_SCHEMA', 'error', '/', sprintf( 'Missing required property "%s".', $required ) );
			}
		}

		if ( array_key_exists( 'version', $tree ) && 1 !== $tree['version'] ) {
			$errors[] = self::make( 'E_TREE_SCHEMA', 'error', '/version', 'Property "version" must be the integer 1.' );
		}

		if ( array_key_exists( 'epoch', $tree ) && ! is_string( $tree['epoch'] ) ) {
			$errors[] = self::make( 'E_TREE_SCHEMA', 'error', '/epoch', 'Property "epoch" must be a string.' );
		}

		if ( array_key_exists( 'blocks', $tree ) ) {
			if ( ! self::is_json_array( $tree['blocks'] ) ) {
				$errors[] = self::make( 'E_TREE_SCHEMA', 'error', '/blocks', 'Property "blocks" must be an array of BlockNode.' );
			} else {
				foreach ( $tree['blocks'] as $index => $node ) {
					$errors = array_merge( $errors, self::check_node_schema( $node, '/blocks/' . $index ) );
				}
			}
		}

		return $errors;
	}

	/**
	 * Recursive BlockNode schema check.
	 *
	 * @param mixed  $node Node.
	 * @param string $path RFC 6901 pointer to the node.
	 * @return array Diagnostics.
	 */
	private static function check_node_schema( $node, string $path ): array {
		if ( ! self::is_json_object( $node ) ) {
			return array( self::make( 'E_TREE_SCHEMA', 'error', $path, 'BlockNode must be an object.' ) );
		}

		$node   = self::to_map( $node );
		$errors = array();

		if ( ! array_key_exists( 'name', $node ) ) {
			$errors[] = self::make( 'E_TREE_SCHEMA', 'error', $path, 'BlockNode is missing required property "name".' );
		} elseif ( ! is_string( $node['name'] ) || ! preg_match( self::BLOCK_NAME_PATTERN, $node['name'] ) ) {
			$errors[] = self::make( 'E_TREE_SCHEMA', 'error', $path . '/name', 'BlockNode "name" must match ^[a-z0-9-]+/[a-z0-9-]+$.' );
		}

		if ( array_key_exists( 'attributes', $node ) && ! self::is_json_object( $node['attributes'] ) ) {
			$errors[] = self::make( 'E_TREE_SCHEMA', 'error', $path . '/attributes', 'BlockNode "attributes" must be an object.' );
		}

		if ( array_key_exists( 'innerBlocks', $node ) ) {
			$inner = $node['innerBlocks'];
			if ( ! self::is_json_array( $inner ) ) {
				$errors[] = self::make( 'E_TREE_SCHEMA', 'error', $path . '/innerBlocks', 'BlockNode "innerBlocks" must be an array of BlockNode.' );
			} else {
				foreach ( $inner as $index => $child ) {
					$errors = array_merge( $errors, self::check_node_schema( $child, $path . '/innerBlocks/' . $index ) );
				}
			}
		}

		// additionalProperties: false. A stray innerHTML is a hard schema error.
		foreach ( array_keys( $node ) as $key ) {
			if ( ! in_array( (string) $key, self::BLOCK_NODE_KEYS, true ) ) {
				$errors[] = self::make(
					'E_TREE_SCHEMA',
					'error',
					$path . '/' . self::escape_pointer_token( (string) $key ),
					sprintf( 'BlockNode does not allow the property "%s". A tree never carries serialized markup; innerHTML is a harness output.', (string) $key )
				);
			}
		}

		return $errors;
	}

	/*
	 * -------------------------------------------------------------------
	 * Semantic walk
	 * -------------------------------------------------------------------
	 */

	/**
	 * Walk a list of nodes.
	 *
	 * @param array       $nodes       Node list.
	 * @param string      $base        Pointer to the list.
	 * @param array       $blocks      Registry blocks map.
	 * @param string|null $parent_name Immediate parent block name, null at root.
	 * @param string[]    $ancestors   Ancestor chain, root first.
	 * @return void
	 */
	private static function walk( array $nodes, string $base, array $blocks, ?string $parent_name, array $ancestors ): void {
		$parent_hints = ( null !== $parent_name && isset( $blocks[ $parent_name ] ) )
			? self::hints_of( $blocks[ $parent_name ] )
			: null;

		foreach ( $nodes as $index => $node ) {
			$path = $base . '/' . $index;
			$node = self::to_map( $node );

			if ( is_array( $parent_hints ) && is_array( $parent_hints['allowed_blocks'] ) && array() !== $parent_hints['allowed_blocks'] ) {
				$name = (string) ( $node['name'] ?? '' );
				if ( ! in_array( $name, $parent_hints['allowed_blocks'], true ) ) {
					self::add(
						'W_HINT_ALLOWED_BLOCKS',
						'warning',
						$path,
						sprintf(
							'Block "%s" is not in the allowed_blocks hint of its container "%s" (%s).',
							$name,
							(string) $parent_name,
							implode( ', ', $parent_hints['allowed_blocks'] )
						),
						'use one of the container\'s allowed_blocks, or move this block out of the container'
					);
				}
			}

			self::visit( $node, $path, $blocks, $parent_name, $ancestors );
		}
	}

	/**
	 * Check one node, then recurse.
	 *
	 * @param array       $node        Node.
	 * @param string      $path        Pointer to the node.
	 * @param array       $blocks      Registry blocks map.
	 * @param string|null $parent_name Immediate parent block name.
	 * @param string[]    $ancestors   Ancestor chain, root first.
	 * @return void
	 */
	private static function visit( array $node, string $path, array $blocks, ?string $parent_name, array $ancestors ): void {
		$name = (string) $node['name'];

		if ( ! isset( $blocks[ $name ] ) ) {
			self::add(
				'E_UNKNOWN_BLOCK',
				'error',
				$path,
				sprintf( 'Block "%s" is not registered on this instance.', $name ),
				'call GET /manifest and pick a block that exists here, or install it via POST /blocks/install'
			);

			// Children of an unknown block are not further checked.
			return;
		}

		$type = $blocks[ $name ];

		self::check_parent( $name, $type, $path, $parent_name );
		self::check_ancestor( $name, $type, $path, $ancestors );
		self::check_attributes( $name, $type, $node, $path );
		self::check_styles( $name, $type, $node, $path );
		self::check_bindings( $name, $node, $path );

		if ( empty( $type['is_dynamic'] ) && ! isset( self::$static_seen[ $name ] ) ) {
			self::$static_seen[ $name ] = true;
			self::add(
				'W_STATIC_NEEDS_HARNESS',
				'warning',
				$path,
				sprintf( 'Block "%s" is static: its markup is defined by its JavaScript save() output.', $name ),
				self::FIX_HINT_STATIC
			);
		}

		$children = ( isset( $node['innerBlocks'] ) && self::is_json_array( $node['innerBlocks'] ) ) ? $node['innerBlocks'] : array();

		$hints = self::hints_of( $type );
		if ( in_array( $hints['template_lock'], array( 'all', 'insert' ), true ) && array() !== $children ) {
			self::add(
				'W_HINT_TEMPLATE_LOCK',
				'warning',
				$path,
				sprintf( 'Block "%s" declares template_lock "%s"; adding inner blocks to it is not supported.', $name, (string) $hints['template_lock'] ),
				'leave this block\'s inner blocks alone, or place your content in an unlocked container'
			);
		}

		if ( array() !== $children ) {
			self::walk( $children, $path . '/innerBlocks', $blocks, $name, array_merge( $ancestors, array( $name ) ) );
		}
	}

	/**
	 * E_NEST_PARENT.
	 *
	 * @param string      $name        Block name.
	 * @param array       $type        Registry entry.
	 * @param string      $path        Node pointer.
	 * @param string|null $parent_name Immediate parent, null at tree root.
	 * @return void
	 */
	private static function check_parent( string $name, array $type, string $path, ?string $parent_name ): void {
		$parents = ( isset( $type['parent'] ) && is_array( $type['parent'] ) ) ? $type['parent'] : array();

		if ( array() === $parents ) {
			return;
		}

		if ( null === $parent_name ) {
			self::add(
				'E_NEST_PARENT',
				'error',
				$path,
				sprintf( 'Block "%s" may only be used inside %s, but it sits at the tree root.', $name, implode( ' or ', $parents ) ),
				sprintf( 'wrap it in %s', $parents[0] )
			);

			return;
		}

		if ( ! in_array( $parent_name, $parents, true ) ) {
			self::add(
				'E_NEST_PARENT',
				'error',
				$path,
				sprintf( 'Block "%s" may only be used inside %s, but its parent is "%s".', $name, implode( ' or ', $parents ), $parent_name ),
				sprintf( 'wrap it in %s', $parents[0] )
			);
		}
	}

	/**
	 * E_NEST_ANCESTOR.
	 *
	 * @param string   $name      Block name.
	 * @param array    $type      Registry entry.
	 * @param string   $path      Node pointer.
	 * @param string[] $ancestors Actual ancestor chain.
	 * @return void
	 */
	private static function check_ancestor( string $name, array $type, string $path, array $ancestors ): void {
		$required = ( isset( $type['ancestor'] ) && is_array( $type['ancestor'] ) ) ? $type['ancestor'] : array();

		if ( array() === $required ) {
			return;
		}

		if ( array() === array_intersect( $required, $ancestors ) ) {
			self::add(
				'E_NEST_ANCESTOR',
				'error',
				$path,
				sprintf(
					'Block "%s" requires one of %s somewhere above it; the actual chain is %s.',
					$name,
					implode( ', ', $required ),
					array() === $ancestors ? '(tree root)' : implode( ' > ', $ancestors )
				),
				sprintf( 'place it inside %s', $required[0] )
			);
		}
	}

	/**
	 * E_ATTR_TYPE / E_ATTR_ENUM / W_ATTR_UNKNOWN.
	 *
	 * @param string $name Block name.
	 * @param array  $type Registry entry.
	 * @param array  $node Node.
	 * @param string $path Node pointer.
	 * @return void
	 */
	/**
	 * W_STYLE_UNKNOWN — an is-style-* className that is not registered
	 * server-side for this block at this fingerprint.
	 *
	 * Deliberately a warning, and deliberately skipped when the block has no
	 * server-registered styles at all: many core styles (image "rounded",
	 * button "outline") register client-side only, where the server is blind —
	 * wp_manifest's client capture is the authority there.
	 *
	 * @param string $name Block name.
	 * @param array  $type Manifest entry (carries `styles` since interfaces v2).
	 * @param array  $node Node.
	 * @param string $path Node pointer.
	 * @return void
	 */
	private static function check_styles( string $name, array $type, array $node, string $path ): void {
		$attrs      = isset( $node['attributes'] ) ? self::to_map( $node['attributes'] ) : array();
		$class_name = $attrs['className'] ?? null;

		if ( ! is_string( $class_name ) || false === strpos( $class_name, 'is-style-' ) ) {
			return;
		}

		$registered = array();
		foreach ( (array) ( $type['styles'] ?? array() ) as $style ) {
			$style = is_array( $style ) ? $style : (array) $style;
			if ( '' !== (string) ( $style['name'] ?? '' ) ) {
				$registered[] = (string) $style['name'];
			}
		}

		if ( array() === $registered ) {
			return;
		}

		foreach ( preg_split( '/\s+/', trim( $class_name ) ) ?: array() as $token ) {
			if ( 0 !== strpos( $token, 'is-style-' ) ) {
				continue;
			}
			$slug = substr( $token, strlen( 'is-style-' ) );
			if ( '' === $slug || 'default' === $slug || in_array( $slug, $registered, true ) ) {
				continue;
			}

			self::add(
				'W_STYLE_UNKNOWN',
				'warning',
				$path . '/attributes/className',
				sprintf( 'Style "%s" is not registered for "%s" at this fingerprint (server-side styles: %s).', $slug, $name, implode( ', ', $registered ) ),
				'pick a registered style from wp_manifest blocks[].styles — client-registered styles appear there under source "client" via the harness capture'
			);
		}
	}

	/**
	 * E_BINDING_UNKNOWN / E_BINDING_UNBINDABLE — attributes.metadata.bindings
	 * must reference a registered binding source and a bindable attribute.
	 *
	 * @param string $name Block name.
	 * @param array  $node Node.
	 * @param string $path Node pointer.
	 * @return void
	 */
	private static function check_bindings( string $name, array $node, string $path ): void {
		$attrs    = isset( $node['attributes'] ) ? self::to_map( $node['attributes'] ) : array();
		$metadata = isset( $attrs['metadata'] ) ? self::to_map( $attrs['metadata'] ) : array();
		$bindings = isset( $metadata['bindings'] ) ? self::to_map( $metadata['bindings'] ) : array();

		if ( array() === $bindings ) {
			return;
		}

		$sources  = self::$platform['binding_sources'];
		$bindable = self::$platform['bindable'];

		foreach ( $bindings as $attr => $binding ) {
			$attr    = (string) $attr;
			$pointer = $path . '/attributes/metadata/bindings/' . self::escape_pointer_token( $attr );
			$binding = self::to_map( $binding );
			$source  = (string) ( $binding['source'] ?? '' );

			if ( is_array( $sources ) && ! in_array( $source, $sources, true ) ) {
				self::add(
					'E_BINDING_UNKNOWN',
					'error',
					$pointer,
					sprintf( 'Binding source "%s" is not registered on this instance.', $source ),
					sprintf( 'registered sources: %s — see wp_manifest section "bindings"', implode( ', ', $sources ) ?: '(none)' )
				);
				continue;
			}

			// '__default' binds the pattern-overrides set, not one attribute.
			if ( '__default' === $attr ) {
				continue;
			}

			if ( isset( $bindable[ $name ] ) ) {
				$allowed = array_map( 'strval', (array) $bindable[ $name ] );
				if ( ! in_array( $attr, $allowed, true ) ) {
					self::add(
						'E_BINDING_UNBINDABLE',
						'error',
						$pointer,
						sprintf( 'Attribute "%s" is not bindable on "%s".', $attr, $name ),
						sprintf( 'bindable attributes on %s: %s', $name, implode( ', ', $allowed ) )
					);
				}
			} elseif ( array() !== $bindable ) {
				self::add(
					'E_BINDING_UNBINDABLE',
					'error',
					$pointer,
					sprintf( 'Block "%s" supports no block bindings on this instance.', $name ),
					'core supports bindings on paragraph content, heading content, image id/url/title/alt and button url/text/linkTarget/rel — see wp_manifest section "bindings"'
				);
			}
		}
	}

	private static function check_attributes( string $name, array $type, array $node, string $path ): void {
		$given = isset( $node['attributes'] ) ? self::to_map( $node['attributes'] ) : array();

		if ( array() === $given ) {
			return;
		}

		$declared = $type['attributes'] ?? array();
		if ( $declared instanceof stdClass ) {
			$declared = (array) $declared;
		}
		$declared = is_array( $declared ) ? $declared : array();

		foreach ( $given as $key => $value ) {
			$key     = (string) $key;
			$pointer = $path . '/attributes/' . self::escape_pointer_token( $key );

			if ( ! array_key_exists( $key, $declared ) ) {
				if ( in_array( $key, self::GLOBAL_ATTRIBUTES, true ) ) {
					continue;
				}

				self::add(
					'W_ATTR_UNKNOWN',
					'warning',
					$pointer,
					sprintf( 'Attribute "%s" is not declared by "%s".', $key, $name ),
					'drop it, or check GET /manifest for the block\'s declared attributes'
				);

				continue;
			}

			$schema = $declared[ $key ];
			if ( $schema instanceof stdClass ) {
				$schema = (array) $schema;
			}
			if ( ! is_array( $schema ) ) {
				continue;
			}

			if ( isset( $schema['type'] ) && ! self::type_matches( $value, $schema['type'] ) ) {
				$expected = is_array( $schema['type'] ) ? implode( '|', array_map( 'strval', $schema['type'] ) ) : (string) $schema['type'];
				self::add(
					'E_ATTR_TYPE',
					'error',
					$pointer,
					sprintf( 'Attribute "%s" of "%s" must be of type %s, got %s.', $key, $name, $expected, self::type_name( $value ) ),
					sprintf( 'supply a %s value', $expected )
				);

				continue;
			}

			if ( isset( $schema['enum'] ) && is_array( $schema['enum'] ) && ! self::enum_matches( $value, $schema['enum'] ) ) {
				self::add(
					'E_ATTR_ENUM',
					'error',
					$pointer,
					sprintf(
						'Attribute "%s" of "%s" must be one of %s.',
						$key,
						$name,
						implode( ', ', array_map( array( __CLASS__, 'scalar_label' ), $schema['enum'] ) )
					),
					'pick one of the enumerated values'
				);
			}
		}
	}

	/*
	 * -------------------------------------------------------------------
	 * Type helpers
	 * -------------------------------------------------------------------
	 */

	/**
	 * JSON-Schema type check over a json_decode(assoc) value.
	 *
	 * `type` may be a string or an array of strings. Types outside the JSON
	 * Schema set (WordPress registers e.g. "rich-text") carry no shape
	 * information here and are not checked -- source-based HTML semantics are
	 * the harness's job.
	 *
	 * @param mixed        $value Value.
	 * @param string|array $type  Declared type.
	 * @return bool
	 */
	public static function type_matches( $value, $type ): bool {
		$types = is_array( $type ) ? $type : array( $type );
		$known = array( 'string', 'number', 'integer', 'boolean', 'array', 'object', 'null' );

		$checked = false;

		foreach ( $types as $candidate ) {
			$candidate = is_string( $candidate ) ? $candidate : '';

			if ( ! in_array( $candidate, $known, true ) ) {
				continue;
			}

			$checked = true;

			switch ( $candidate ) {
				case 'string':
					if ( is_string( $value ) ) {
						return true;
					}
					break;
				case 'number':
					if ( ( is_int( $value ) || is_float( $value ) ) && ! is_bool( $value ) ) {
						return true;
					}
					break;
				case 'integer':
					if ( is_int( $value ) ) {
						return true;
					}
					if ( is_float( $value ) && floor( $value ) === $value ) {
						return true;
					}
					break;
				case 'boolean':
					if ( is_bool( $value ) ) {
						return true;
					}
					break;
				case 'array':
					// An empty array is indistinguishable from an empty object
					// after json_decode( $body, true ); accept it for both.
					if ( is_array( $value ) && ( array() === $value || array_is_list( $value ) ) ) {
						return true;
					}
					break;
				case 'object':
					if ( $value instanceof stdClass ) {
						return true;
					}
					if ( is_array( $value ) && ( array() === $value || ! array_is_list( $value ) ) ) {
						return true;
					}
					break;
				case 'null':
					if ( null === $value ) {
						return true;
					}
					break;
			}
		}

		// No recognisable JSON Schema type was declared: nothing to assert.
		return ! $checked;
	}

	/**
	 * Enum membership, loose about int/float equality but strict about type class.
	 *
	 * @param mixed $value Value.
	 * @param array $enum  Allowed values.
	 * @return bool
	 */
	public static function enum_matches( $value, array $enum ): bool {
		foreach ( $enum as $allowed ) {
			if ( $allowed === $value ) {
				return true;
			}
			if ( is_numeric( $allowed ) && is_numeric( $value ) && ! is_string( $allowed ) && ! is_string( $value ) && (float) $allowed === (float) $value ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Human name for a decoded JSON value's type.
	 *
	 * @param mixed $value Value.
	 * @return string
	 */
	public static function type_name( $value ): string {
		if ( null === $value ) {
			return 'null';
		}
		if ( is_bool( $value ) ) {
			return 'boolean';
		}
		if ( is_int( $value ) ) {
			return 'integer';
		}
		if ( is_float( $value ) ) {
			return 'number';
		}
		if ( is_string( $value ) ) {
			return 'string';
		}
		if ( $value instanceof stdClass ) {
			return 'object';
		}
		if ( is_array( $value ) ) {
			return array_is_list( $value ) ? 'array' : 'object';
		}

		return 'unknown';
	}

	/**
	 * Printable label for an enum member.
	 *
	 * @param mixed $value Value.
	 * @return string
	 */
	public static function scalar_label( $value ): string {
		if ( is_bool( $value ) ) {
			return $value ? 'true' : 'false';
		}
		if ( null === $value ) {
			return 'null';
		}
		if ( is_scalar( $value ) ) {
			return (string) $value;
		}

		return self::type_name( $value );
	}

	/*
	 * -------------------------------------------------------------------
	 * Plumbing
	 * -------------------------------------------------------------------
	 */

	/**
	 * Agent hints for a registry entry, defaults filled in.
	 *
	 * @param array $type Registry entry.
	 * @return array
	 */
	private static function hints_of( array $type ): array {
		$defaults = array(
			'allowed_blocks'     => null,
			'template_lock'      => null,
			'usage_notes'        => '',
			'example_attributes' => array(),
		);

		$hints = $type['agent_hints'] ?? array();
		if ( $hints instanceof stdClass ) {
			$hints = (array) $hints;
		}

		return array_merge( $defaults, is_array( $hints ) ? $hints : array() );
	}

	/**
	 * True when a decoded value stands for a JSON object.
	 *
	 * A body decoded with objects preserved gives stdClass for every JSON
	 * object, so the test is exact there. Associative arrays are accepted too
	 * (json_decode with assoc, and PHP-built trees in tests); the one residual
	 * ambiguity is an empty PHP array, which is treated as an empty object.
	 *
	 * @param mixed $value Value.
	 * @return bool
	 */
	private static function is_json_object( $value ): bool {
		if ( $value instanceof stdClass ) {
			return true;
		}

		return is_array( $value ) && ( array() === $value || ! array_is_list( $value ) );
	}

	/**
	 * True when a decoded value stands for a JSON array.
	 *
	 * stdClass never qualifies, so `"innerBlocks": {}` is a schema error.
	 *
	 * @param mixed $value Value.
	 * @return bool
	 */
	private static function is_json_array( $value ): bool {
		return is_array( $value ) && array_is_list( $value );
	}

	/**
	 * Decoded JSON object as an associative array.
	 *
	 * @param mixed $value Value.
	 * @return array
	 */
	private static function to_map( $value ): array {
		if ( $value instanceof stdClass ) {
			return (array) $value;
		}

		return is_array( $value ) ? $value : array();
	}

	/**
	 * RFC 6901 token escaping: ~ -> ~0, / -> ~1.
	 *
	 * @param string $token Raw token.
	 * @return string
	 */
	public static function escape_pointer_token( string $token ): string {
		return str_replace( array( '~', '/' ), array( '~0', '~1' ), $token );
	}

	/**
	 * Build a diagnostic.
	 *
	 * @param string      $code      Diagnostic code.
	 * @param string      $severity  error|warning.
	 * @param string      $path      RFC 6901 pointer.
	 * @param string      $message   Human text.
	 * @param string|null $fix_hint  Optional hint.
	 * @return array
	 */
	private static function make( string $code, string $severity, string $path, string $message, ?string $fix_hint = null ): array {
		$diagnostic = array(
			'code'     => $code,
			'severity' => $severity,
			'path'     => $path,
			'message'  => $message,
		);

		if ( null !== $fix_hint ) {
			$diagnostic['fix_hint'] = $fix_hint;
		}

		return $diagnostic;
	}

	/**
	 * Append a diagnostic to the current run.
	 *
	 * @param string      $code     Diagnostic code.
	 * @param string      $severity error|warning.
	 * @param string      $path     RFC 6901 pointer.
	 * @param string      $message  Human text.
	 * @param string|null $fix_hint Optional hint.
	 * @return void
	 */
	private static function add( string $code, string $severity, string $path, string $message, ?string $fix_hint = null ): void {
		self::$diagnostics[] = self::make( $code, $severity, $path, $message, $fix_hint );
	}

	/**
	 * Assemble the Diagnostics document.
	 *
	 * @param array  $diagnostics        Diagnostics.
	 * @param bool   $epoch_ok           Epoch comparison result.
	 * @param string $server_fingerprint Current epoch.
	 * @return array
	 */
	private static function document( array $diagnostics, bool $epoch_ok, string $server_fingerprint ): array {
		$valid = true;
		foreach ( $diagnostics as $diagnostic ) {
			if ( 'error' === $diagnostic['severity'] ) {
				$valid = false;
				break;
			}
		}

		return array(
			'valid'              => $valid,
			'epoch_ok'           => $epoch_ok,
			'server_fingerprint' => $server_fingerprint,
			'diagnostics'        => array_values( $diagnostics ),
		);
	}
}
